export const wordBanks = {
    1: [
        { en: "abandon", he: "לנטוש" }, { en: "ability", he: "יכולת" }, { en: "abolish", he: "לבטל" },
        { en: "absence", he: "היעדרות" }, { en: "absorb", he: "לספוג" }, { en: "absurd", he: "אבסורדי" },
        { en: "abundant", he: "שופע" }, { en: "abuse", he: "להתעלל" }, { en: "accelerate", he: "להאיץ" },
        { en: "accept", he: "לקבל" }, { en: "access", he: "גישה" }, { en: "accommodate", he: "לארח" },
        { en: "accompany", he: "ללוות" }, { en: "accomplish", he: "להשיג" }, { en: "account", he: "חשבון" },
        { en: "accumulate", he: "לצבור" }, { en: "accurate", he: "מדויק" }, { en: "accuse", he: "להאשים" },
        { en: "achieve", he: "להשיג" }, { en: "acknowledge", he: "להכיר ב" }, { en: "acquire", he: "לרכוש" },
        { en: "adapt", he: "להסתגל" }, { en: "adequate", he: "הולם" }, { en: "adjust", he: "להתאים" },
        { en: "administer", he: "לנהל" }, { en: "admire", he: "להעריץ" }, { en: "admit", he: "להודות" },
        { en: "adopt", he: "לאמץ" }, { en: "advance", he: "להתקדם" }, { en: "advantage", he: "יתרון" },
        { en: "adversity", he: "מצוקה" }, { en: "advocate", he: "לתמוך ב" }, { en: "affect", he: "להשפיע" },
        { en: "afford", he: "להרשות לעצמו" }, { en: "agency", he: "סוכנות" }, { en: "aggressive", he: "תוקפני" },
        { en: "agree", he: "להסכים" }, { en: "agriculture", he: "חקלאות" }, { en: "aid", he: "סיוע" },
        { en: "aim", he: "מטרה" }, { en: "alert", he: "עירני" }, { en: "alien", he: "זר" },
        { en: "align", he: "ליישר" }, { en: "allege", he: "לטעון" }, { en: "alleviate", he: "להקל" },
        { en: "allow", he: "להרשות" }, { en: "ally", he: "בעל ברית" }, { en: "alter", he: "לשנות" },
        { en: "alternative", he: "חלופה" }, { en: "ambiguous", he: "דו-משמעי" }, { en: "ambition", he: "שאיפה" },
        { en: "amend", he: "לתקן" }, { en: "ample", he: "שופע" }, { en: "amuse", he: "לשעשע" },
        { en: "analyze", he: "לנתח" }, { en: "ancestor", he: "אב קדמון" }, { en: "ancient", he: "עתיק" },
        { en: "anger", he: "כעס" }, { en: "angle", he: "זווית" }, { en: "announce", he: "להודיע" },
        { en: "annual", he: "שנתי" }, { en: "anticipate", he: "לצפות" }, { en: "anxiety", he: "חרדה" },
        { en: "apologize", he: "להתנצל" }, { en: "apparent", he: "גלוי" }, { en: "appeal", he: "לפנות" },
        { en: "appear", he: "להופיע" }, { en: "applaud", he: "למחוא כפיים" }, { en: "apply", he: "ליישם" },
        { en: "appoint", he: "למנות" }, { en: "appreciate", he: "להעריך" }, { en: "approach", he: "לגשת" },
        { en: "appropriate", he: "הולם" }, { en: "approve", he: "לאשר" }, { en: "approximate", he: "משוער" },
        { en: "arbitrary", he: "שרירותי" }, { en: "argue", he: "לטעון" }, { en: "arise", he: "להתעורר" },
        { en: "armed", he: "חמוש" }, { en: "arouse", he: "לעורר" }, { en: "arrange", he: "לסדר" },
        { en: "arrest", he: "לעצור" }, { en: "arrive", he: "להגיע" }, { en: "arrogant", he: "יהיר" },
        { en: "art", he: "אמנות" }, { en: "article", he: "מאמר" }, { en: "artificial", he: "מלאכותי" },
        { en: "ascend", he: "לעלות" }, { en: "ashamed", he: "נבוך" }, { en: "aside", he: "הצידה" },
        { en: "ask", he: "לשאול" }, { en: "aspect", he: "היבט" }, { en: "assemble", he: "להרכיב" },
        { en: "assert", he: "לטעון" }, { en: "assess", he: "להעריך" }, { en: "asset", he: "נכס" },
        { en: "assign", he: "להקצות" }, { en: "assist", he: "לסייע" }, { en: "associate", he: "לקשר" },
        { en: "assume", he: "להניח" }, { en: "assure", he: "להבטיח" }, { en: "astonish", he: "להדהים" },
        { en: "attach", he: "לצרף" }, { en: "attack", he: "לתקוף" }, { en: "attain", he: "להשיג" },
        { en: "attempt", he: "לנסות" }, { en: "attend", he: "להשתתף" }, { en: "attention", he: "תשומת לב" },
        { en: "attitude", he: "גישה" }, { en: "attract", he: "למשוך" }, { en: "attribute", he: "לייחס" },
        { en: "audience", he: "קהל" }, { en: "authentic", he: "אותנטי" }, { en: "author", he: "סופר" },
        { en: "authority", he: "סמכות" }, { en: "authorize", he: "להסמיך" }, { en: "automatic", he: "אוטומטי" },
        { en: "available", he: "זמין" }, { en: "average", he: "ממוצע" }, { en: "avoid", he: "להימנע" },
        { en: "aware", he: "מודע" }, { en: "awesome", he: "מדהים" }, { en: "awful", he: "נורא" },
        { en: "awkward", he: "מגושם" }, { en: "axis", he: "ציר" }, { en: "background", he: "רקע" },
        { en: "balance", he: "איזון" }, { en: "ban", he: "לאסור" }, { en: "band", he: "להקה" },
        { en: "bare", he: "חשוף" }, { en: "bargain", he: "מציאה" }, { en: "barrier", he: "מחסום" },
        { en: "base", he: "בסיס" }, { en: "basic", he: "בסיסי" }, { en: "battle", he: "קרב" },
        { en: "bear", he: "לשאת" }, { en: "beat", he: "להכות" }, { en: "beautiful", he: "יפה" },
        { en: "because", he: "בגלל" }, { en: "become", he: "להפוך" }, { en: "before", he: "לפני" },
        { en: "begin", he: "להתחיל" }, { en: "behalf", he: "בשם" }, { en: "behave", he: "להתנהג" },
        { en: "behind", he: "מאחורי" }, { en: "belief", he: "אמונה" }, { en: "belong", he: "להשתייך" },
        { en: "below", he: "מתחת" }, { en: "bend", he: "לכופף" }, { en: "beneficial", he: "מועיל" },
        { en: "benefit", he: "תועלת" }, { en: "beside", he: "ליד" }, { en: "besides", he: "חוץ מזה" },
        { en: "bet", he: "להתערב" }, { en: "betray", he: "לבגוד" }, { en: "between", he: "בין" },
        { en: "beware", he: "להיזהר" }, { en: "beyond", he: "מעבר" }, { en: "bias", he: "דעה קדומה" },
        { en: "bid", he: "הצעת מחיר" }, { en: "bind", he: "לקשור" }, { en: "biography", he: "ביוגרפיה" },
        { en: "birth", he: "לידה" }, { en: "bite", he: "לנשוך" }, { en: "bitter", he: "מר" },
        { en: "blame", he: "להאשים" }, { en: "blank", he: "ריק" }, { en: "blast", he: "פיצוץ" },
        { en: "blend", he: "לערבב" }, { en: "bless", he: "לברך" }, { en: "blind", he: "עיוור" },
        { en: "block", he: "לחסום" }, { en: "blood", he: "דם" }, { en: "blow", he: "לנשוף" },
        { en: "board", he: "לוח" }, { en: "boast", he: "להתרברב" }, { en: "body", he: "גוף" },
        { en: "boil", he: "להרתיח" }, { en: "bold", he: "אמיץ" }, { en: "bomb", he: "פצצה" }
    ],
    2: [ /* מאגר 2 - ניתן להוסיף מילים כאן */ ],
    3: [ /* מאגר 3 - ניתן להוסיף מילים כאן */ ],
    4: [ /* מאגר 4 - ניתן להוסיף מילים כאן */ ],
    5: [ /* מאגר 5 - ניתן להוסיף מילים כאן */ ],
    6: [ /* מאגר 6 - ניתן להוסיף מילים כאן */ ],
    7: [ /* מאגר 7 - ניתן להוסיף מילים כאן */ ],
    8: [ /* מאגר 8 - ניתן להוסיף מילים כאן */ ],
    9: [ /* מאגר 9 - ניתן להוסיף מילים כאן */ ],
    10: [ /* מאגר 10 - ניתן להוסיף מילים כאן */ ],
};
