export const wordBanks = {
    1: [
        { en: "abandon", he: "לנטוש" }, { en: "ability", he: "יכולת" }, { en: "abolish", he: "לבטל" },
        { en: "absence", he: "היעדרות" }, { en: "absorb", he: "לספוג" }, { en: "absurd", he: "אבסורדי" },
        { en: "abundant", he: "שופע" }, { en: "abuse", he: "להתעלל" }, { en: "accelerate", he: "להאיץ" },
        { en: "accept", he: "לקבל" }, { en: "access", he: "גישה" }, { en: "accommodate", he: "לארח" },
        { en: "accompany", he: "ללוות" }, { en: "accomplish", he: "להשיג" }, { en: "account", he: "חשבון" },
        { en: "accumulate", he: "לצבור" }, { en: "accurate", he: "מדויק" }, { en: "accuse", he: "להאשים" },
        { en: "achieve", he: "להשיג" }, { en: "acknowledge", he: "להכיר ב" }, { en: "acquire", he: "לרכוש" },
        { en: "adapt", he: "להסתגל" }, { en: "adequate", he: "הולם" }, { en: "adjust", he: "להתאים" },
        { en: "administer", he: "לנהל" }, { en: "admire", he: "להעריץ" }, { en: "admit", he: "להודות" },
        { en: "adopt", he: "לאמץ" }, { en: "advance", he: "להתקדם" }, { en: "advantage", he: "יתרון" },
        { en: "adversity", he: "מצוקה" }, { en: "advocate", he: "לתמוך ב" }, { en: "affect", he: "להשפיע" },
        { en: "afford", he: "להרשות לעצמו" }, { en: "agency", he: "סוכנות" }, { en: "aggressive", he: "תוקפני" },
        { en: "agree", he: "להסכים" }, { en: "agriculture", he: "חקלאות" }, { en: "aid", he: "סיוע" },
        { en: "aim", he: "מטרה" }, { en: "alert", he: "עירני" }, { en: "alien", he: "זר" },
        { en: "align", he: "ליישר" }, { en: "allege", he: "לטעון" }, { en: "alleviate", he: "להקל" },
        { en: "allow", he: "להרשות" }, { en: "ally", he: "בעל ברית" }, { en: "alter", he: "לשנות" },
        { en: "alternative", he: "חלופה" }, { en: "ambiguous", he: "דו-משמעי" }, { en: "ambition", he: "שאיפה" },
        { en: "amend", he: "לתקן" }, { en: "ample", he: "שופע" }, { en: "amuse", he: "לשעשע" },
        { en: "analyze", he: "לנתח" }, { en: "ancestor", he: "אב קדמון" }, { en: "ancient", he: "עתיק" },
        { en: "anger", he: "כעס" }, { en: "angle", he: "זווית" }, { en: "announce", he: "להודיע" },
        { en: "annual", he: "שנתי" }, { en: "anticipate", he: "לצפות" }, { en: "anxiety", he: "חרדה" },
        { en: "apologize", he: "להתנצל" }, { en: "apparent", he: "גלוי" }, { en: "appeal", he: "לפנות" },
        { en: "appear", he: "להופיע" }, { en: "applaud", he: "למחוא כפיים" }, { en: "apply", he: "ליישם" },
        { en: "appoint", he: "למנות" }, { en: "appreciate", he: "להעריך" }, { en: "approach", he: "לגשת" },
        { en: "appropriate", he: "הולם" }, { en: "approve", he: "לאשר" }, { en: "approximate", he: "משוער" },
        { en: "arbitrary", he: "שרירותי" }, { en: "argue", he: "לטעון" }, { en: "arise", he: "להתעורר" },
        { en: "armed", he: "חמוש" }, { en: "arouse", he: "לעורר" }, { en: "arrange", he: "לסדר" },
        { en: "arrest", he: "לעצור" }, { en: "arrive", he: "להגיע" }, { en: "arrogant", he: "יהיר" },
        { en: "art", he: "אמנות" }, { en: "article", he: "מאמר" }, { en: "artificial", he: "מלאכותי" },
        { en: "ascend", he: "לעלות" }, { en: "ashamed", he: "נבוך" }, { en: "aside", he: "הצידה" },
        { en: "ask", he: "לשאול" }, { en: "aspect", he: "היבט" }, { en: "assemble", he: "להרכיב" },
        { en: "assert", he: "לטעון" }, { en: "assess", he: "להעריך" }, { en: "asset", he: "נכס" },
        { en: "assign", he: "להקצות" }, { en: "assist", he: "לסייע" }, { en: "associate", he: "לקשר" },
        { en: "assume", he: "להניח" }, { en: "assure", he: "להבטיח" }, { en: "astonish", he: "להדהים" },
        { en: "attach", he: "לצרף" }, { en: "attack", he: "לתקוף" }, { en: "attain", he: "להשיג" },
        { en: "attempt", he: "לנסות" }, { en: "attend", he: "להשתתף" }, { en: "attention", he: "תשומת לב" },
        { en: "attitude", he: "גישה" }, { en: "attract", he: "למשוך" }, { en: "attribute", he: "לייחס" },
        { en: "audience", he: "קהל" }, { en: "authentic", he: "אותנטי" }, { en: "author", he: "סופר" },
        { en: "authority", he: "סמכות" }, { en: "authorize", he: "להסמיך" }, { en: "automatic", he: "אוטומטי" },
        { en: "available", he: "זמין" }, { en: "average", he: "ממוצע" }, { en: "avoid", he: "להימנע" },
        { en: "aware", he: "מודע" }, { en: "awesome", he: "מדהים" }, { en: "awful", he: "נורא" },
        { en: "awkward", he: "מגושם" }, { en: "axis", he: "ציר" }, { en: "background", he: "רקע" },
        { en: "balance", he: "איזון" }, { en: "ban", he: "לאסור" }, { en: "band", he: "להקה" },
        { en: "bare", he: "חשוף" }, { en: "bargain", he: "מציאה" }, { en: "barrier", he: "מחסום" },
        { en: "base", he: "בסיס" }, { en: "basic", he: "בסיסי" }, { en: "battle", he: "קרב" },
        { en: "bear", he: "לשאת" }, { en: "beat", he: "להכות" }, { en: "beautiful", he: "יפה" },
        { en: "because", he: "בגלל" }, { en: "become", he: "להפוך" }, { en: "before", he: "לפני" },
        { en: "begin", he: "להתחיל" }, { en: "behalf", he: "בשם" }, { en: "behave", he: "להתנהג" },
        { en: "behind", he: "מאחורי" }, { en: "belief", he: "אמונה" }, { en: "belong", he: "להשתייך" },
        { en: "below", he: "מתחת" }, { en: "bend", he: "לכופף" }, { en: "beneficial", he: "מועיל" },
        { en: "benefit", he: "תועלת" }, { en: "beside", he: "ליד" }, { en: "besides", he: "חוץ מזה" },
        { en: "bet", he: "להתערב" }, { en: "betray", he: "לבגוד" }, { en: "between", he: "בין" },
        { en: "beware", he: "להיזהר" }, { en: "beyond", he: "מעבר" }, { en: "bias", he: "דעה קדומה" },
        { en: "bid", he: "הצעת מחיר" }, { en: "bind", he: "לקשור" }, { en: "biography", he: "ביוגרפיה" },
        { en: "birth", he: "לידה" }, { en: "bite", he: "לנשוך" }, { en: "bitter", he: "מר" },
        { en: "blame", he: "להאשים" }, { en: "blank", he: "ריק" }, { en: "blast", he: "פיצוץ" },
        { en: "blend", he: "לערבב" }, { en: "bless", he: "לברך" }, { en: "blind", he: "עיוור" },
        { en: "block", he: "לחסום" }, { en: "blood", he: "דם" }, { en: "blow", he: "לנשוף" },
        { en: "board", he: "לוח" }, { en: "boast", he: "להתרברב" }, { en: "body", he: "גוף" },
        { en: "boil", he: "להרתיח" }, { en: "bold", he: "אמיץ" }, { en: "bomb", he: "פצצה" }
    ],
    
2: [
    { en: "ability", he: "יכולת" },
    { en: "able", he: "יכול, מסוגל" },
    { en: "accept", he: "לקבל" },
    { en: "acceptable", he: "מקובל" },
    { en: "acceptance", he: "הסכמה" },
    { en: "accident", he: "תאונה" },
    { en: "achieve", he: "להשיג" },
    { en: "activate", he: "להפעיל" },
    { en: "active", he: "פעיל" },
    { en: "actor", he: "שחקן" },
    { en: "actual", he: "ממשי" },
    { en: "actually", he: "למעשה" },
    { en: "addition", he: "תוספת, הוספה" },
    { en: "address", he: "לפנות, לטפל" },
    { en: "address", he: "כתובת" },
    { en: "adjust", he: "להתרגל" },
    { en: "adjust", he: "לכוונן" },
    { en: "afford", he: "יכל לעמוד בהוצאות" },
    { en: "afraid", he: "מפחד" },
    { en: "agree", he: "להסכים" },
    { en: "agreement", he: "הסכם" },
    { en: "aim", he: "לכוון, מטרה" },
    { en: "alarm", he: "דאגה, להדאיג" },
    { en: "alarm", he: "אזעקה" },
    { en: "alive", he: "חי" },
    { en: "almost", he: "כמעט" },
    { en: "alone", he: "לבד" },
    { en: "alternate", he: "התחלף, עבר מדבר אחד לשני וחזרה" },
    { en: "alternate", he: "חלופי" },
    { en: "altogether", he: "לגמרי" },
    { en: "ambassador", he: "שגריר" },
    { en: "ambiguous", he: "דו משמעי, לא לגמרי ברור" },
    { en: "amount", he: "כמות" },
    { en: "anger", he: "כעס, להכעיס" },
    { en: "angry", he: "כועס" },
    { en: "animal", he: "חיה" },
    { en: "another", he: "נוסף" },
    { en: "another", he: "אחר" },
    { en: "answer", he: "תשובה" },
    { en: "apart", he: "בנפרד" },
    { en: "apology", he: "התנצלות" },
    { en: "appear", he: "להופיע" },
    { en: "appear", he: "נראה ש-" },
    { en: "appearance", he: "מראה, הופעה" },
    { en: "appropriate", he: "מתאים" },
    { en: "approve", he: "לאשר" },
    { en: "architect", he: "ארכיטקט" },
    { en: "architecture", he: "אדריכלות, ארכיטקטורה" },
    { en: "area", he: "אזור, תחום" },
    { en: "argue", he: "להתווכח" },
    { en: "argument", he: "ויכוח" },
    { en: "aristocrat", he: "אציל, אריסטוקרט" },
    { en: "arm", he: "לחמש" },
    { en: "arm", he: "זרוע" },
    { en: "army", he: "צבא" },
    { en: "around", he: "בערך" },
    { en: "arrange", he: "לסדר" },
    { en: "arrest", he: "מעצר, לעצור" },
    { en: "arrive", he: "להגיע" },
    { en: "art", he: "אמנות" },
    { en: "article", he: "פריט" },
    { en: "article", he: "מאמר" },
    { en: "articulate", he: "רהוט" },
    { en: "articulate", he: "להביע" },
    { en: "artist", he: "אמן" },
    { en: "artistic", he: "אמנותי" },
    { en: "as far as", he: "לגבי, בכל הנוגע ל-" },
    { en: "as proof of", he: "כהוכחה ל-" },
    { en: "ask", he: "לשאול" },
    { en: "asked for", he: "ביקש" },
    { en: "associate", he: "לקשר" },
    { en: "association", he: "אסוציאציה" },
    { en: "association", he: "איגוד" },
    { en: "assume", he: "להניח" },
    { en: "assumption", he: "הנחה" },
    { en: "at least", he: "לפחות" },
    { en: "athlete", he: "ספורטאי, אתלט" },
    { en: "attach", he: "לחבר, ליחס" },
    { en: "attack", he: "לתקוף, מתקפה" },
    { en: "attempt", he: "ניסיון" },
    { en: "attitude", he: "גישה" },
    { en: "attract", he: "למשוך" },
    { en: "attraction", he: "משיכה" },
    { en: "attractive", he: "נאה, מושך" },
    { en: "audience", he: "קהל" },
    { en: "authentic", he: "מקורי, אותנטי" },
    { en: "availability", he: "זמינות" },
    { en: "available", he: "זמין" },
    { en: "average", he: "ממוצע, רגיל" },
    { en: "avoid", he: "להתחמק, להימנע" },
    { en: "awake", he: "ער, להתעורר" },
    { en: "bacteria", he: "חיידקים" },
    { en: "badly", he: "נואשות, קשות" },
    { en: "baker", he: "אופה" },
    { en: "band", he: "להקה" },
    { en: "band", he: "לחבוש, תחבושת, רצועה" },
    { en: "barely", he: "בקושי" },
    { en: "base", he: "בסיס" },
    { en: "bat", he: "עטלף" },
    { en: "bat", he: "מחבט" },
    { en: "bath", he: "אמבטיה, להתרחץ" },
    { en: "battle", he: "מאבק, להיאבק" },
    { en: "beach", he: "חוף ים" },
    { en: "bear", he: "דוב" },
    { en: "bear", he: "לסבול, לשאת" },
    { en: "beauty", he: "יופי" },
    { en: "bedroom", he: "חדר שינה" },
    { en: "begin/began/begun", he: "להתחיל / התחיל / התחיל" },
    { en: "beginning", he: "התחלה" },
    { en: "belong", he: "שייך" },
    { en: "best", he: "הכי טוב" },
    { en: "best-seller", he: "רב- מכר" },
    { en: "better", he: "טוב יותר" },
    { en: "bicycle", he: "אופניים" },
    { en: "birth", he: "לידה" },
    { en: "bite", he: "לנשוך, נשיכה" },
    { en: "bizarre", he: "מוזר" },
    { en: "blind", he: "עיוור" },
    { en: "block", he: "לבנה, גוש, חלק" },
    { en: "block", he: "חסימה" },
    { en: "blood", he: "דם" },
    { en: "blood vessel", he: "כלי דם" },
    { en: "blow, blew", he: "לנשוף, נשף" },
    { en: "blow, blew", he: "לפוצץ, פוצץ" },
    { en: "boat", he: "סירה" },
    { en: "body", he: "גוויה, גוף" },
    { en: "bone", he: "עצם" },
    { en: "border", he: "גבול" },
    { en: "boring", he: "משעמם" },
    { en: "bottle", he: "בקבוק" },
    { en: "bottom", he: "תחתית" },
    { en: "bottom", he: "ישבן" },
    { en: "bought", he: "קנה" },
    { en: "brain", he: "מוח, שכל" },
    { en: "brainwash", he: "לשטוף את המח" },
    { en: "brave", he: "אמיץ" },
    { en: "bread", he: "לחם" },
    { en: "break", he: "לשבור" },
    { en: "breathe", he: "לנשום" },
    { en: "bridge", he: "גשר, לגשר" },
    { en: "broad", he: "נרחב" },
    { en: "budget", he: "תקציב, לתקצב" },
    { en: "build", he: "לבנות" },
    { en: "build", he: "מבנה" },
    { en: "building", he: "בניין" },
    { en: "built", he: "לבנות" },
    { en: "bullet", he: "קליע" },
    { en: "by", he: "באמצעות, על- ידי" },
    { en: "call", he: "לקרוא, להתקשר" },
    { en: "camera", he: "מצלמה" },
    { en: "care", he: "לחבב" },
    { en: "care", he: "לדאוג, לטפל" },
    { en: "carefully", he: "בזהירות" },
    { en: "careless", he: "לא זהיר, רשלני" },
    { en: "carry", he: "לסחוב" },
    { en: "catalogue", he: "קטלוג, רשימת פריטים" },
    { en: "catch, caught", he: "לתפוס, תפס" },
    { en: "cause", he: "מטרה" },
    { en: "cause", he: "גורם, סיבה" },
    { en: "cell", he: "תא" },
    { en: "center", he: "מרכז" },
    { en: "central", he: "מרכזי" },
    { en: "challenge", he: "לאתגר" },
    { en: "challenge", he: "אתגר" },
    { en: "chance", he: "סיכוי" },
    { en: "change", he: "עודף" },
    { en: "change", he: "שינוי, לשנות" },
    { en: "characterize", he: "לאפיין" },
    { en: "cheap", he: "זול" },
    { en: "check", he: "לבדוק" },
    { en: "child", he: "ילד" },
    { en: "childhood", he: "ילדות" },
    { en: "children", he: "ילדים" },
    { en: "circle", he: "להקיף בעיגול" },
    { en: "circle", he: "מעגל" },
    { en: "clean", he: "נקי, לנקות" },
    { en: "clever", he: "פיקח" },
    { en: "climb", he: "לטפס" },
    { en: "clock", he: "שעון" },
    { en: "close", he: "סגור, לסגור" },
    { en: "cloth", he: "בגד, בד" },
    { en: "coach", he: "מאמן, לאמן, להדריך" },
    { en: "coach", he: "קרון נוסעים, כרכרה, מחלקת תיירים (במטוס)" },
    { en: "code", he: "קוד" },
    { en: "coexist", he: "להתקיים בשותפות" },
    { en: "coin", he: "מטבע" },
    { en: "cold", he: "קר, התקררות" },
    { en: "colonial", he: "קולוניאלי" },
    { en: "color", he: "לצבוע" },
    { en: "color", he: "צבע" },
    { en: "complain", he: "להתלונן" },
    { en: "complete", he: "כולל" },
    { en: "complete", he: "להשלים" },
    { en: "consist", he: "מורכב מ-" },
    { en: "contact", he: "ליצור קשר, מגע" },
    { en: "continue", he: "להמשיך" },
    { en: "continuity", he: "המשכיות, רצף הגיוני" },
    { en: "continuous", he: "מתמשך" },
    { en: "control", he: "לוח בקרה, פיקוח" },
    { en: "control", he: "שליטה, לשלוט" },
    { en: "cool", he: "לצנן, צונן" },
    { en: "copies", he: "עותקים" },
    { en: "copy", he: "להעתיק" },
    { en: "corner", he: "פינה, לדחוק לפינה" },
    { en: "correct", he: "לתקן" },
    { en: "correct", he: "נכון" },
    { en: "cost", he: "מחיר, עלות" },
    { en: "costly", he: "יקר" },
    { en: "count", he: "לספור" },
    { en: "count", he: "רוזן" },
    { en: "country", he: "ארץ" },
    { en: "country", he: "כפר, אזור" },
    { en: "cover", he: "כיסוי, מכסה" },
    { en: "cow", he: "פרה" },
    { en: "culture", he: "תרבות" },
    { en: "dance", he: "לרקוד" },
    { en: "danger", he: "סכנה, לסכן" },
    { en: "dangerous", he: "מסוכן" },
    { en: "daughter", he: "בת" },
    { en: "death", he: "מוות" },
    { en: "deep", he: "עמוק" },
    { en: "deeply", he: "מאוד, במידה רבה" },
    { en: "define", he: "להגדיר" },
    { en: "definite", he: "מוחלט" },
    { en: "delete", he: "למחוק" },
    { en: "desert", he: "מדבר" },
    { en: "desert", he: "לנטוש" },
    { en: "devastate", he: "להחריב" },
    { en: "die", he: "מת, למות" },
    { en: "die (dice)", he: "קובייה (קוביות)" },
    { en: "difficult", he: "קשה" },
    { en: "dirty", he: "מלוכלך" },
    { en: "diverse", he: "מגוון" },
    { en: "done", he: "גמור, עשוי" },
    { en: "dream", he: "חלום, לחלום" },
    { en: "drink", he: "לשתות, משקה" },
    { en: "drug", he: "סם, תרופה, לסמם" },
    { en: "due", he: "צריך להיעשות, זמנו הגיע" },
    { en: "due", he: "בשל" },
    { en: "early", he: "מוקדם" },
    { en: "earth", he: "אדמה" },
    { en: "Earth", he: "כדור הארץ" },
    { en: "earthquake", he: "רעידת אדמה" },
    { en: "educate", he: "לחנך" },
    { en: "education", he: "השכלה" },
    { en: "empty", he: "ריק, לרוקן" },
    { en: "enemy", he: "אויב" },
    { en: "energy", he: "אנרגיה, כוח" },
    { en: "enjoy", he: "ליהנות" },
    { en: "enjoyable", he: "מהנה" },
    { en: "enter", he: "נכנס" },
    { en: "error", he: "שגיאה" },
    { en: "escape", he: "לברוח, בריחה" },
    { en: "evening", he: "ערב" },
    { en: "event", he: "אירוע" },
    { en: "exact", he: "מדויק" },
    { en: "exactly", he: "בדיוק" },
    { en: "example", he: "דוגמה" },
    { en: "excessive", he: "יתר, מוגזם" },
    { en: "expert", he: "מומחה" },
    { en: "extinct", he: "נכחד" },
    { en: "fact", he: "עובדה" },
    { en: "false", he: "שקר" },
    { en: "farm", he: "חווה" },
    { en: "farmer", he: "חוואי" },
    { en: "father", he: "אבא" },
    { en: "fear", he: "פחד, לפחד" },
    { en: "feel", he: "להרגיש" },
    { en: "feeling", he: "הרגשה" },
    { en: "few", he: "מעט" },
    { en: "field", he: "תחום, שדה" },
    { en: "find", he: "למצוא" },
    { en: "findings", he: "ממצאים" },
    { en: "finger", he: "אצבע" },
    { en: "fire", he: "לפטר" },
    { en: "fire", he: "אש, להצית" },
    { en: "fire", he: "לירות" },
    { en: "fix", he: "לתקן" },
    { en: "flower", he: "פרח" },
    { en: "forget", he: "לשכוח" },
    { en: "friend", he: "חבר" },
    { en: "friendly", he: "ידידותי" },
    { en: "friendship", he: "חברות" },
    { en: "front", he: "חזית, להתעמת" },
    { en: "full", he: "מלא, למלא" },
    { en: "gain", he: "להרוויח, להוסיף" },
    { en: "glad", he: "שמח" },
    { en: "gradual", he: "הדרגתי" },
    { en: "great", he: "גדול, מעולה" },
    { en: "half", he: "חצי" },
    { en: "hand", he: "יד" },
    { en: "hand", he: "למסור" },
    { en: "hear", he: "לשמוע" },
    { en: "hearsay", he: "שמועה" },
    { en: "heat", he: "חום, לחמם" },
    { en: "hero", he: "גיבור" },
    { en: "horse", he: "סוס" },
    { en: "hot", he: "חם" },
    { en: "hot", he: "חריף" },
    { en: "house", he: "לשכן" },
    { en: "house", he: "בית" },
    { en: "impartial", he: "אוביקטיבי, ללא צד" },
    { en: "inconsistent", he: "לא עקבי" },
    { en: "insert", he: "להכניס" },
    { en: "jump", he: "לקפוץ" },
    { en: "just", he: "מדויק, אמיתי" },
    { en: "just", he: "צודק, הוגן" },
    { en: "just", he: "רק, בלבד" },
    { en: "kill", he: "להרוג, לחסל, הרג" },
    { en: "king", he: "מלך" },
    { en: "kingdom", he: "ממלכה" },
    { en: "kitchen", he: "מטבח" },
    { en: "last", he: "המשיך, החזיק מעמד" },
    { en: "late", he: "מאוחר, לאחר" },
    { en: "light", he: "קל" },
    { en: "light", he: "אור" },
    { en: "like", he: "לחבב, להעדיף" },
    { en: "list", he: "רשימה, להכין רשימה" },
    { en: "lock", he: "מנעול, לנעול" },
    { en: "logic", he: "הגיון" },
    { en: "main", he: "עיקרי" },
    { en: "map", he: "מפה, למפות" },
    { en: "mark", he: "לסמן" },
    { en: "maybe", he: "אולי" },
    { en: "meeting", he: "פגישה" },
    { en: "member", he: "חבר (בקבוצה מסוימת)" },
    { en: "milk", he: "חלב, לחלוב" },
    { en: "mistake", he: "טעות" },
    { en: "mistaken", he: "שגוי, לטעות" },
    { en: "money", he: "כסף" },
    { en: "move", he: "לזוז, לעבור" },
    { en: "movement", he: "תנועה" },
    { en: "must", he: "חייב, חובה, הכרח" },
    { en: "number", he: "מספר" },
    { en: "once", he: "פעם אחת" },
    { en: "open", he: "לפתוח, פתוח" },
    { en: "over", he: "מחדש, שוב" },
    { en: "paragraph", he: "פִסקה" },
    { en: "pay", he: "לשלם" },
    { en: "peace", he: "שלום" },
    { en: "peaceful", he: "שָׁלֵו, שקט" },
    { en: "pilot", he: "טייס" },
    { en: "place", he: "מקום, למקם" },
    { en: "plan", he: "לתכנן" },
    { en: "plan", he: "תכנית" },
    { en: "plane", he: "מטוס" },
    { en: "plane", he: "מישור" },
    { en: "president", he: "נשיא" },
    { en: "price", he: "מחיר" },
    { en: "primary", he: "יסודי, עיקרי" },
    { en: "problem", he: "בעיה" },
    { en: "program", he: "תכנית" },
    { en: "program", he: "תכניה" },
    { en: "program", he: "לתכנת" },
    { en: "queen", he: "מלכה" },
    { en: "question", he: "להטיל ספק" },
    { en: "question", he: "שאלה" },
    { en: "quick", he: "זריז" },
    { en: "rates", he: "שיעור , היקף, תעריף" },
    { en: "rather", he: "למדי" },
    { en: "react", he: "להגיב" },
    { en: "region", he: "מחוז, אזור" },
    { en: "register", he: "להירשם" },
    { en: "registration", he: "הרשמה" },
    { en: "reject", he: "לדחות" },
    { en: "rest", he: "מנוחה" },
    { en: "rest", he: "יתר, שאר" },
    { en: "rich", he: "עשיר" },
    { en: "right", he: "זכות" },
    { en: "risk", he: "סיכון, לסכן" },
    { en: "river", he: "נהר" },
    { en: "road", he: "דרך" },
    { en: "safe", he: "בטוח" },
    { en: "safety", he: "בטיחות" },
    { en: "save", he: "לשמור" },
    { en: "scare", he: "פחד, להפחיד" },
    { en: "school", he: "בית- ספר" },
    { en: "search", he: "חיפוש, לחפש" },
    { en: "select", he: "לבחור" },
    { en: "sell", he: "למכור" },
    { en: "send", he: "לשלוח" },
    { en: "several", he: "אחדים, כמה" },
    { en: "short", he: "קצר" },
    { en: "shortage", he: "מחסור" },
    { en: "side", he: "צד, לצודד, לתמוך" },
    { en: "sleep", he: "שינה" },
    { en: "sleep", he: "לישון" },
    { en: "slow", he: "איטי, לאט" },
    { en: "slow down", he: "להאט" },
    { en: "so", he: "כל- כך, מאוד" },
    { en: "space", he: "חלל" },
    { en: "space", he: "רווח" },
    { en: "speed", he: "מהירות" },
    { en: "start", he: "להתחיל" },
    { en: "still", he: "נייח, דומם, שקט" },
    { en: "stone", he: "אבן" },
    { en: "strong", he: "חזק" },
    { en: "stronghold", he: "מאחז" },
    { en: "system", he: "מערכת" },
    { en: "system", he: "שיטה" },
    { en: "target", he: "מטרה" },
    { en: "teach, taught", he: "ללמד, לימד" },
    { en: "think, thought", he: "לחשוב, חשב" },
    { en: "time", he: "זמן" },
    { en: "totally", he: "לחלוטין" },
    { en: "town", he: "עיר, עיירה" },
    { en: "understand", he: "להבין" },
    { en: "unusual", he: "בלתי רגיל, יוצא דופן" },
    { en: "use", he: "תועלת, תכלית" },
    { en: "use", he: "לנצל" },
    { en: "use", he: "להשתמש" },
    { en: "useful", he: "שימושי" },
    { en: "useless", he: "חסר תועלת" },
    { en: "usual", he: "רגיל" },
    { en: "valuable", he: "יקר ערך" },
    { en: "value", he: "ערך, להעריך" },
    { en: "view", he: "לראות" },
    { en: "view", he: "נוף, שדה ראיה" },
    { en: "viewer", he: "צופה" },
    { en: "visit", he: "לבקר" },
    { en: "visitor", he: "אורח, מבקר" },
    { en: "voice", he: "קול, להשמיע קול" },
    { en: "wait", he: "להמתין, המתנה" },
    { en: "way", he: "דרך" },
    { en: "weather", he: "מזג אוויר" },
    
     ],
    3: [ /* מאגר 3 - ניתן להוסיף מילים כאן */ ],
    4: [ /* מאגר 4 - ניתן להוסיף מילים כאן */ ],
    5: [ /* מאגר 5 - ניתן להוסיף מילים כאן */ ],
    6: [ /* מאגר 6 - ניתן להוסיף מילים כאן */ ],
    7: [ /* מאגר 7 - ניתן להוסיף מילים כאן */ ],
    8: [ /* מאגר 8 - ניתן להוסיף מילים כאן */ ],
    9: [ /* מאגרר 9 - ניתן להוסיף מילים כאן */ ],
    10: [ /* מאגר 10 - ניתן להוסיף מילים כאן */ ],
};
